Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
ClassAndModuleChildren:
  EnforcedStyle: compact
# Rails/TopLevelInclude:
#   Include:
#     - app/**/*.rb
